apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: test
  namespace: default
  labels:
    stable.k8s.psg.io/kcm.class: "kube-cert-manager"
spec:
  domain: "test.littlefluffyclouds.io"
